- name: create genesis folder
  file:
    path: "{{ output_genesis_path }}"
    state: directory
    owner: sovereign
    group: sovereign
  become: true
  become_user: root

- name: render rollup genesis.json
  become: true
  become_user: sovereign
  ansible.builtin.template:
    src: "genesis.json.j2"
    dest: "{{ output_genesis_path }}/genesis.json"
  vars:
    genesis_attester_rollup_address: "{{ genesis_sequencer_rollup_address }}"
    genesis_da_height: "{{ da_start_height }}"