- name: copy service file to remote server
  ansible.builtin.template:
    src: rollup.service.j2
    dest: /etc/systemd/system/rollup.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: copy rollup shell file to remote server
  ansible.builtin.template:
    src: rollup.sh.j2
    dest: /home/sovereign/rollup.sh
    owner: sovereign
    group: sovereign
    mode: '0755'
  become: true

- name: stop rollup service
  ansible.builtin.systemd:
    name: rollup
    state: stopped
  become: true

- name: wipe rollup data using helper script
  ansible.builtin.command: /home/ubuntu/wipe-rollup-data.sh
  become: true
  when: wipe | bool

- name: reload systemd to recognize rollup service
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: start rollup service
  ansible.builtin.systemd:
    name: rollup
    state: started
    enabled: yes
  become: true

- name: wait for rollup service to be active
  ansible.builtin.systemd:
    name: rollup
  register: result
  until: result.status.ActiveState == "active" and result.status.SubState == "running"
  retries: 30
  delay: 10
  become: true