# Hyperlane Role Defaults

# Git
hyperlane_repo: "https://github.com/Sovereign-Labs/hyperlane-monorepo.git"
hyperlane_commit_hash: ""
hyperlane_branch: "integration"
hyperlane_repo_dir: "hyperlane-monorepo"

# Build
debug: false
hyperlane_log_level: "info"
hyperlane_agent_config_path: "/home/sovereign/config/agent-config.json"

# Custom RPC URLs per chain (defined in secrets)
hyperlane_custom_rpc_urls: {}

# Custom index.from block number per chain (optional)
# Specifies the block number from which to start indexing for each chain
hyperlane_chain_index_from:
  sepolia: 9872667

# Target chain config (used in agent-config.json)
hyperlane_target_chain: "sovstarter"
hyperlane_target_signer_type: "sovereignKey"
hyperlane_target_signer_account_type: "ethereum"
hyperlane_rollup_url: ""
hyperlane_is_testnet: true

# Checkpoint syncer (S3) - mandatory when validator is enabled
hyperlane_checkpoint_syncer_bucket: ""
hyperlane_checkpoint_syncer_region: ""
hyperlane_checkpoint_syncer_folder: ""

# Validator
# If hyperlane_validator_origin_chain is defined, validator runs as systemd service
hyperlane_validator_origin_chain: ""
hyperlane_validator_metrics_port: 9092
hyperlane_validator_db_path: "{{ rollup_storage_dir }}/hyperlane-validator"

# Relayer
# If hyperlane_relayer_relay_chains is defined, relayer runs as systemd service
hyperlane_relayer_relay_chains: ""
hyperlane_relayer_metrics_port: 9091
hyperlane_relayer_db_path: "{{ rollup_storage_dir }}/hyperlane-relayer"