---
# Rollup Configuration

# GitHub repository settings
# Full git URL - use HTTPS for public repos, git@github.com: for private repos with SSH keys
rollup_repo: "https://github.com/Sovereign-Labs/rollup-starter.git"
rollup_repo_dir: "rollup-starter"

# Git commit hash for the sovereign rollup repository
# Update this to deploy a specific version
# Main branch on 2025-11-13
rollup_commit_hash: "770a88a25576640b1e76b9385bf61b05452d60dd"
# TODO: branch
# Commit takes higher prio
rollup_branch: "master"

# Build configuration
rollup_bin: "rollup"
# Can be `risc0` or `mock_zkvm`
zkvm_role: "mock_zkvm"
debug: true
is_rollup_replica: false

# Genesis configuration
genesis_folder: "/home/sovereign/genesis"
# This is for particular instance.
# Currently it goes to genesis as a single preferred sequencer. TODO: follow up: support for different sequencer at genesis
rollup_sequencer_address: "0xA6edfca3AA985Dd3CC728BFFB700933a986aC085"

# Network ports
rollup_http_host: "127.0.0.1"
rollup_http_port: 12346
# TODO: Optional nginx
nginx_port: 8081

# Wipe rollup data directory on deployment (use with caution)
wipe: false

# Service configuration
max_open_files: 1000000
grafana_telemetry_enabled: true

# Optional PostgreSQL connection string for sequencer
# rollup_sequencer_postgres_connection_string: "postgresql://user:pass@host/db"
