---
- name: update-initramfs
  become: true
  command: update-initramfs -u

- name: restart journald
  become: true
  systemd:
    name: systemd-journald
    state: restarted

- name: restart telegraf
  become: true
  systemd:
    name: telegraf
    state: restarted

- name: restart alloy
  become: true
  systemd:
    name: alloy
    state: restarted
