---
# Celestia DA Configuration

# Common variables, but with different values
# Cargo feature name for building with Celestia DA
da_feature: "celestia_da"
# DA start height for the rollup
da_start_height: 8877186
# Should be derived from signer_private_key
da_rollup_address: "celestia1jk6xx55wum73al8f2mp54x92uggqws8ksnjus2"

# Celestia specific variables
# [NOTE: Length cannot change - must be exactly 10 characters]
rollup_batch_namespace: "sov-b-dev8"
rollup_proof_namespace: "sov-p-dev8"

# These values are overridden from vars/celestia_secrets.yaml
# Defaults are provided here but should be replaced with actual secrets
# External Celestia RPC endpoints
celestia_rpc_url: ""
celestia_grpc_url: ""
celestia_grpc_auth_token: ""
signer_private_key: ""
